"""
brief_generator.py
Pre-call brief generator for the Outbound Hunter.

Triggered when a meeting is booked (via UI button on an approved prospect card).
Builds a structured brief and saves it to:
  1. The prospect record in the DB (pre_call_brief column)
  2. A HubSpot deal note attached to the prospect's deal (if hs_deal_id is set)

The brief has two layers:
  - Static sections built locally from the prospect dict + niche library
    (post text, signal phrase, ICP notes, niche context, call opener)
  - Dynamic sections generated by Claude
    (demo angle, objection response, three discovery questions)

Usage:
    from brief_generator import generate_and_save
    result = generate_and_save(prospect_id)
    # returns {"ok": True, "brief": "...", "note_id": "...", "hs_error": None}
"""

import os
import json
import urllib.request
import urllib.error
from datetime import datetime, timezone

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
MODEL             = "claude-sonnet-4-6"
HUBSPOT_TOKEN     = os.environ.get("HUBSPOT_TOKEN", "")
_HS_BASE          = "https://api.hubapi.com"


# ── Niche helper ──────────────────────────────────────────────────────────────

def _get_niche_module(niche_slug):
    if not niche_slug:
        return None
    try:
        from scrapers.niches import get_niche
        return get_niche(niche_slug)
    except Exception:
        return None


# ── AI section ────────────────────────────────────────────────────────────────

_AI_SYSTEM = """You are a sales coach preparing a founder for a 20-minute B2B discovery call.
The founder sells AltusFlow — an automated growth system built on three components:
  1. A website AI assistant that qualifies leads and books calls 24/7
  2. Meta Ads funnels that turn cold traffic into booked calls
  3. An outbound AI that finds prospects who are actively signalling intent

Your job: write three sharp sections for the pre-call brief.
Tailor everything to this specific prospect — their post text is the firepower.
Be concrete. No filler. No corporate speak.

Output exactly these three sections with exactly these headers (no preamble, no explanation):

RECOMMENDED DEMO ANGLE
[2-3 sentences. Which of the three AltusFlow components maps most directly to this person's
pain? Lead with that. Why is it the right fit for their specific situation?]

HANDLING THEIR LIKELY OBJECTION
Objection: [restate the objection in their words/voice]
Response: [2-3 sentences. Acknowledge, reframe, bridge to a concrete question.]

THREE DISCOVERY QUESTIONS
1. [Pain depth — how long has this been a problem, what have they already tried]
2. [Opportunity size — what is one new client worth to them, what's the annual value]
3. [Current process — what are they doing right now to solve this, how is it working]"""


def _generate_ai_section(name, title, company, post_text, niche_label, deal_econ, objection):
    """
    Call Claude to generate the dynamic brief sections.
    Returns a formatted string block.
    Falls back to a placeholder if API key is missing or the call fails.
    """
    if not ANTHROPIC_API_KEY:
        return (
            "RECOMMENDED DEMO ANGLE\n"
            "[Add ANTHROPIC_API_KEY to .env to enable AI-generated sections]\n\n"
            "HANDLING THEIR LIKELY OBJECTION\n"
            f"Objection: {objection or 'See niche library'}\n"
            "Response: [Not generated]\n\n"
            "THREE DISCOVERY QUESTIONS\n"
            "1. [Not generated]\n"
            "2. [Not generated]\n"
            "3. [Not generated]"
        )

    user_prompt = (
        f"Prospect: {name} — {title} at {company}\n"
        f"Niche: {niche_label}\n"
        f"Deal economics: {deal_econ}\n"
        f"Likely objection: {objection}\n\n"
        f"Their exact post:\n\"{post_text}\"\n\n"
        "Write the three sections now."
    )

    payload = {
        "model":      MODEL,
        "max_tokens": 600,
        "system":     _AI_SYSTEM,
        "messages":   [{"role": "user", "content": user_prompt}],
    }

    try:
        req = urllib.request.Request(
            "https://api.anthropic.com/v1/messages",
            data=json.dumps(payload).encode(),
            headers={
                "x-api-key":         ANTHROPIC_API_KEY,
                "anthropic-version": "2023-06-01",
                "Content-Type":      "application/json",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as r:
            data = json.loads(r.read())
        return data["content"][0]["text"].strip()

    except Exception as e:
        return (
            f"RECOMMENDED DEMO ANGLE\n"
            f"[Claude API error: {type(e).__name__}: {e}]\n\n"
            f"HANDLING THEIR LIKELY OBJECTION\n"
            f"Objection: {objection or 'See niche library'}\n"
            f"Response: [Retry by clicking Generate Brief again]\n\n"
            f"THREE DISCOVERY QUESTIONS\n"
            f"1. [Retry]\n2. [Retry]\n3. [Retry]"
        )


# ── Brief builder ─────────────────────────────────────────────────────────────

def generate_brief(prospect):
    """
    Build a complete pre-call brief for this prospect dict.
    Static sections are assembled locally; AI sections come from Claude.
    Returns the brief as a plain-text string.
    """
    name          = (prospect.get("name") or prospect.get("handle") or "Unknown")
    first_name    = name.split()[0]
    title         = prospect.get("title") or "professional"
    company       = prospect.get("company") or "Unknown company"
    post_text     = prospect.get("post_text") or ""
    signal_phrase = prospect.get("signal_phrase") or ""
    icp_score     = prospect.get("icp_score") or 0
    icp_notes     = prospect.get("icp_notes") or ""
    call_opener   = prospect.get("call_opener") or ""
    platform      = (prospect.get("platform") or "linkedin").capitalize()
    outreach_method = prospect.get("outreach_method") or "direct"
    niche_slug    = prospect.get("niche_segment") or prospect.get("niche") or ""
    today         = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    niche_mod   = _get_niche_module(niche_slug)
    niche_label = getattr(niche_mod, "NICHE_LABEL", niche_slug or "Unknown")
    deal_econ   = getattr(niche_mod, "DEAL_ECONOMICS", "")
    objection   = getattr(niche_mod, "COMMON_OBJECTIONS", "")

    # Reddit prospects: flag that outreach is via LinkedIn
    outreach_note = ""
    if outreach_method == "find_linkedin":
        linkedin_url = prospect.get("linkedin_search_url", "")
        outreach_note = (
            f"\nNOTE: Found on Reddit — reach via LinkedIn search:\n{linkedin_url}\n"
        )

    ai_section = _generate_ai_section(
        name=first_name, title=title, company=company,
        post_text=post_text, niche_label=niche_label,
        deal_econ=deal_econ, objection=objection,
    )

    brief = f"""PRE-CALL BRIEF — {name} | {niche_label}
{'=' * 50}
Date: {today}   |   ICP: {icp_score}/10   |   Source: {platform}
Company: {company}
Title: {title}
{outreach_note}
WHAT THEY SAID
--------------
"{post_text}"

Signal matched: "{signal_phrase}"

WHY THEY QUALIFIED
------------------
{icp_notes}

NICHE CONTEXT
-------------
Niche: {niche_label}
Deal economics: {deal_econ}
Likely objection: {objection}

HOW TO OPEN THE CALL
--------------------
{call_opener}

{ai_section}
{'=' * 50}
Generated by AltusFlow Outbound Hunter — {today}"""

    return brief.strip()


# ── HubSpot note ──────────────────────────────────────────────────────────────

def _post_note_to_deal(deal_id, brief_text):
    """
    Create a HubSpot note associated with a deal. Returns note_id.
    Raises RuntimeError on failure.
    """
    if not HUBSPOT_TOKEN:
        raise RuntimeError("HUBSPOT_TOKEN not configured")
    if not deal_id:
        raise RuntimeError("No deal_id — push to HubSpot first")

    payload = json.dumps({
        "properties": {
            "hs_note_body": brief_text,
            "hs_timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z"),
        },
        "associations": [{
            "to":    {"id": deal_id},
            "types": [{"associationCategory": "HUBSPOT_DEFINED", "associationTypeId": 214}],
        }],
    }).encode()

    req = urllib.request.Request(
        f"{_HS_BASE}/crm/v3/objects/notes",
        data=payload,
        headers={
            "Authorization": f"Bearer {HUBSPOT_TOKEN}",
            "Content-Type":  "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            resp = json.loads(r.read())
            return resp["id"]
    except urllib.error.HTTPError as e:
        body = e.read().decode(errors="replace")
        raise RuntimeError(f"HubSpot note failed ({e.code}): {body[:300]}")


# ── Main entry point ──────────────────────────────────────────────────────────

def generate_and_save(prospect_id):
    """
    Full flow: load prospect → generate brief → save to DB → post to HubSpot deal note.

    The HubSpot step is best-effort: if the deal hasn't been pushed yet, or
    HubSpot is unavailable, the brief is still saved to the DB and returned.

    Returns:
        {"ok": True,  "brief": "...", "note_id": "...", "hs_error": None}
        {"ok": False, "error": "...", "step": "load|generate|db"}
    """
    from database import get_prospect, save_pre_call_brief

    # ── Load ──────────────────────────────────────────────────────────────────
    prospect = get_prospect(prospect_id)
    if not prospect:
        return {"ok": False, "error": f"Prospect #{prospect_id} not found", "step": "load"}

    # ── Generate ──────────────────────────────────────────────────────────────
    try:
        brief = generate_brief(prospect)
    except Exception as e:
        return {"ok": False, "error": str(e), "step": "generate"}

    # ── Save to DB ────────────────────────────────────────────────────────────
    try:
        save_pre_call_brief(prospect_id, brief)
    except Exception as e:
        return {"ok": False, "error": str(e), "step": "db"}

    # ── Post to HubSpot deal note (best-effort) ───────────────────────────────
    note_id  = None
    hs_error = None
    deal_id  = prospect.get("hs_deal_id")
    if deal_id:
        try:
            note_id = _post_note_to_deal(deal_id, brief)
        except Exception as e:
            hs_error = str(e)
    else:
        hs_error = "No hs_deal_id on prospect — push to HubSpot first"

    return {"ok": True, "brief": brief, "note_id": note_id, "hs_error": hs_error}


if __name__ == "__main__":
    # Local preview — disables Claude call so you see the brief structure
    os.environ.setdefault("ANTHROPIC_API_KEY", "")

    test = {
        "id":            1,
        "name":          "Sarah Chen",
        "title":         "Founder & CFP",
        "company":       "Chen Financial Group",
        "platform":      "linkedin",
        "post_text":     (
            "Anyone know a good lead gen strategy for financial advisors? "
            "My pipeline has completely dried up and I'm struggling to find qualified clients."
        ),
        "signal_phrase": "pipeline dried up",
        "icp_score":     9,
        "icp_notes":     (
            "Niche title match: 'cfp' | Niche post signal: ['advisor'] | "
            "Decision maker: 'founder' | Strong intent: 6 phrases | "
            "Post asks a question | Full profile available"
        ),
        "call_opener":   (
            "Hey Sarah — I read your post about your pipeline drying up. "
            "That's the most common thing I hear from advisors right now."
        ),
        "niche_segment": "financial-advisors",
        "outreach_method": "direct",
        "hs_deal_id":    None,
    }

    print(generate_brief(test))
